1. Test ACE module

Test results: 
    1) environment variables not added (see https://pypi.org/project/ase/ , section Installation) - failed
    2) run command 'ace test' in the terminal (see https://pypi.org/project/ase/ , section Testing) - failed due to item 1) above
    3) run command 'ace test' in the notebook cell - failed, see below
    4) run example script (see https://pypi.org/project/ase/ , section Example) - failed, see below

Conclusion: ACE module is not properly installed

In [6]:
!ase test

About to run pytest with these parameters:
    -v
Test session starts (platform: linux, Python 3.8.18, pytest 7.4.3, pytest-sugar 0.9.7)
/usr/local/lib/python3.8/dist-packages/hypothesis/_settings.py:74: HypothesisWarning: The database setting is not configured, and the default location is unusable - falling back to an in-memory database for this session.  path=PosixPath('/usr/local/lib/python3.8/dist-packages/ase/test/.hypothesis/examples')
  result = ExampleDatabase(not_set)
cachedir: .pytest_cache
hypothesis profile 'default' -> database=InMemoryExampleDatabase({})
INTERNALERROR> Traceback (most recent call last):
INTERNALERROR>   File "/usr/local/lib/python3.8/dist-packages/_pytest/main.py", line 269, in wrap_session
INTERNALERROR>     config.hook.pytest_sessionstart(session=session)
INTERNALERROR>   File "/usr/local/lib/python3.8/dist-packages/pluggy/_hooks.py", line 493, in __call__
INTERNALERROR>     return self._hookexec(self.name, self._hookimpls, kwargs, firstresult)
INTERNAL

In [5]:
from ase import Atoms
from ase.optimize import BFGS
from ase.calculators.nwchem import NWChem
from ase.io import write

h2 = Atoms('H2',positions=[[0, 0, 0],[0, 0, 0.7]])
h2.calc = NWChem(xc='PBE')
opt = BFGS(h2, trajectory='h2.traj')
opt.run(fmax=0.02)

/bin/sh: 1: nwchem: not found


CalculationFailed: Calculator "nwchem" failed with command "nwchem nwchem.nwi > nwchem.nwo" failed in /home/coder/project with error code 127

2. Testing scipy module

In [3]:
# NB: if the project consists of folder 'tests' then it is not accessible 
# since there is another folder 'tests' in '/usr/local/lib/python3.8/dist-packages'
# and this folder PRECIDES user's folder '/home/coder/project/tests' in the envirinment variable $PATH 
# so the user is forced to rename itsown folder 'tests'
import tests
import matscipy_tests
print(tests.__path__)
print(matscipy_tests.__path__)


['/usr/local/lib/python3.8/dist-packages/tests']
['/home/coder/project/matscipy_tests']


In [4]:
# import sys
# sys.path.insert(0, './tests_')
# from matscipy.neighbours import neighbour_list
# from tests_ import matscipytest
# from tests_ import test_angle_distribution as t

!python3 matscipy_tests/test_angle_distribution.py

....
----------------------------------------------------------------------
Ran 4 tests in 0.001s

OK


In [36]:
def test_small_cell():
        a = ase.Atoms('C', positions=[[0.5, 0.5, 0.5]], cell=[1, 1, 1],
                      pbc=True)
        i, j, dr, shift = neighbour_list("ijDS", a, 1.1)
        assert np.bincount(i)[0] == 6
        assert (dr == shift).all()
        display(i)

        i, j = neighbour_list("ij", a, 1.5)
        assert np.bincount(i)[0] == 18
        display(i)

        a.set_pbc(False)
        i = neighbour_list("i", a, 1.1)
        assert len(i) == 0
        display(i)

        a.set_pbc([True, False, False])
        i = neighbour_list("i", a, 1.1)
        assert np.bincount(i)[0] == 2
        display(i)

        a.set_pbc([True, False, True])
        i = neighbour_list("i", a, 1.1)
        assert np.bincount(i)[0] == 4
        display(i)

test_small_cell()

array([0, 0, 0, 0, 0, 0], dtype=int32)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=int32)

array([], dtype=int32)

array([0, 0], dtype=int32)

array([0, 0, 0, 0], dtype=int32)

In [22]:
import unittest

unittest.main()

usage: ipykernel_launcher.py [-h] [-v] [-q] [--locals] [-f] [-c] [-b]
                             [-k TESTNAMEPATTERNS]
                             [tests [tests ...]]
ipykernel_launcher.py: error: argument -f/--failfast: ignored explicit argument '/home/coder/.local/share/jupyter/runtime/kernel-v2-1318s8RL61gaFgq.json'


AttributeError: 'tuple' object has no attribute 'tb_frame'

In [24]:
from matscipy_tests import *

try:
    from scipy.interpolate import InterpolatedUnivariateSpline
except:
    print('No scipy.interpolate.InterpolatedUnivariateSpline, skipping '
          'EAM test.')
else:
    from matscipy_tests/eam_calculator import *
    from rotation_of_elastic_constants import *


try:
    from scipy.optimize import minimize
except:
    print('No scipy.optimize.minimise, skipping '
          'dislocation test.')
else:
    from test_dislocation import *


SyntaxError: invalid syntax (3590981752.py, line 9)

In [30]:
import matscipy
matscipy.__path__

['/usr/local/lib/python3.8/dist-packages/matscipy']

In [28]:
from matscipy import calculators
calculators.

In [19]:
import numpy as np
from matscipy.neighbours import neighbour_list
rdf_cutoff = 10.0
rdf_nbins = 100

import ase.io as io
a = io.read('aC.cfg')

FileNotFoundError: [Errno 2] No such file or directory: 'aC.cfg'

In [14]:
import scipy, ase
import numpy as np

def test_out_of_bounds():
        nat = 10
        atoms = ase.Atoms(numbers=range(nat),
                          cell=[(0.2, 1.2, 1.4),
                                (1.4, 0.1, 1.6),
                                (1.3, 2.0, -0.1)])
        atoms.set_scaled_positions(3 * np.random.random((nat, 3)) - 1)
        
        for p1 in range(2):
            for p2 in range(2):
                for p3 in range(2):
                    atoms.set_pbc((p1, p2, p3))
                    i, j, d, D, S = neighbour_list("ijdDS", atoms, atoms.numbers * 0.2 + 0.5)
                    c = np.bincount(i)
                    atoms2 = atoms.repeat((p1 + 1, p2 + 1, p3 + 1))
                    i2, j2, d2, D2, S2 = neighbour_list("ijdDS", atoms2, atoms2.numbers * 0.2 + 0.5)
                    c2 = np.bincount(i2)
                    c2.shape = (-1, nat)
                    dd = d.sum() * (p1 + 1) * (p2 + 1) * (p3 + 1) - d2.sum()
                    dr = np.linalg.solve(atoms.cell.T, (atoms.positions[1]-atoms.positions[0]).T).T+np.array([0,0,3])
                    # self.assertTrue(abs(dd) & lt; 1e-10)
                    assert(not (c2 - c).any())

test_out_of_bounds()

NameError: name 'neighbour_list' is not defined